import sys
configfile: 'config/config.yaml'

##### load rules #####
include: "rules/common.smk"

##### organize samples #####
df_ill,var_ill=organizer_illumina()
df_ont,var_ont=organizer_nanopore()
outvar='ill_ont'

if not var_ont:

	now=datetime.now().strftime('%d/%m/%Y %H:%M:%S')
	print('[' + now + ']' + '[Error] Nanopore date must be available for the experiment')
	sys.exit(1)

else:

    if not var_ill:

        now=datetime.now().strftime('%d/%m/%Y %H:%M:%S')
        print('[' + now + ']' + '[Warning] Illumina data are not available. Will use only nanopore data')
        outvar='ont'

##### organize reference #####
organizer_reference()
