import sys
from datetime import datetime
configfile: 'config/config.yaml'

##### load rules #####
include: 'rules/common.smk'
include: 'rules/align.smk'

##### organize samples #####
df_ill,var_ill=organizer_illumina()
df_ont,var_ont=organizer_nanopore()
outvar='ill_ont'

if not var_ont:

	now=datetime.now().strftime('%d/%m/%Y %H:%M:%S')
	print('[' + now + ']' + '[Error] Nanopore date must be available for the experiment')
	sys.exit(1)

else:

	if not var_ill:

		now=datetime.now().strftime('%d/%m/%Y %H:%M:%S')
		print('[' + now + ']' + '[Warning] Illumina data are not available. Will use only nanopore data')
		outvar='ont'

##### organize reference #####
organizer_reference()

##### main rules #####
rule sicelore:
	input:
		expand('results/ill_ont/sicelore/cellranger/{sample}/outs/possorted_genome_bam', sample=df_ill['sample_id'].tolist())