#substitute this with a path to reference
reference: /processing_data/reference_datasets/10xgenomics/2020-A/refdata-gex-GRCh38-2020-A

#configs for all tools on single dataset

sicelcore_data:
  threads: 10
  mem: 100000
  time: "36:00:00"
  expect_cells: 200
  kit: 3prime
  version: v2